name: Deploy .NET Core 3.1 to Azure Container Registry

on:
  push:
    branches:
      - master

env:
  AZURE_CONTAINER_REGISTRY: slavazureregistry.azurecr.io  # Replace with your ACR login server
  IMAGE_NAME: azure-registry-sample  # Replace with your ACR repository name
  TAG: ${{ github.run_number }}

jobs:
  build-and-push:
    name: Build and Push to ACR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        cd AzureContainersSample
        docker build -t $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:$TAG -f Dockerfile .
        docker tag $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:$TAG $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:latest
        docker push $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:$TAG
        docker push $AZURE_CONTAINER_REGISTRY/$IMAGE_NAME:latest
